
development:
  adapter: sqlserver
  database: DMECentral_DEV
  host: localhost
  username: dmeadmin
  password: admin
  pool: 5
  timeout: 5000

test:
  adapter: sqlserver
  database: DMECentral_QA
  host: localhost
  username: dmeadmin
  password: admin
  pool: 5
  timeout: 5000

production:
  adapter: sqlserver
  database: DMECentral_PRD
  host: localhost
  username: dmeadmin
  password: admin
  pool: 5
  timeout: 5000